### ISSUE TITLE
how to use a jupyter nb  when a newbie ?

### ISSUE THREAD

**Issue by md342010** [samirdeshpande/MINDS#1]
Hi,

thanks to have created a github repository ! We waited it for months :o)
But I have some troubles to use it, as a newbie with a Jupyter environment...
I have some questions to install and run MINDS and also some precisions to help next users. My OS is Mac OS X, with python3.
First, on my terminal, I downloaded MINDS with git in my local Applications folder: so I have a folder MINDS with a code subfolder :

Applications
|__ MINDS
|__ LICENSE.md
|__ README.md
|__ code
|             |__ MINDS.jpynb
|__ requirements.yml

```
cd MINDS
conda env create --file requirements.yml'
``` 
it didn't work for me. The error message was :
```
"Solving environment: failed
ResolvePackageNotFound:"
```
following a list with +70 packages...

I don't know if something is missing from MINDS git or in my computer. I updated conda (miniconda3 already installed), installed manualy some packages, make several google requests...
Anyway, I activate MINDS environment, created projects folder then MINDS, then subfolders code/ as written in the readme, including the 'code' subfolder.
So I have  both code folders : one Applications/MINDS/code/MINDS.jpynb 
and on Applications/MINDS/projects/MINDS/code (empty)

Then the readme says to go to projects/MINDS/code, tape 'jupyter notebook' then click on MINDS.jpynb. But MINDS.ppynb is in Applications/MINDS/code downloaded with git, not in projects/MINDS/code (which is empty, isn't it ?)

I suggest the help should indicate :
- download MINDS with git
- go to MINDS
- conda blablabla / activate env / ...
- mkdir centrifuge_db centrifuge_rslts docs fastq logs reports

Then we have something like :
Applications
   |__ MINDS
            |__ LICENSE.md
            |__ README.md
            |__ code
            |          |__ MINDS.jpynb
            |__ requirements.yml
            |__ centrifuge_db
            |__ centrifuge_rslts
            |__ docs
            |__ fastq
            |__ logs
            |__ reports

Secondly, I don't use Jupyter so I'm quite lost with this GUI. I change the path of the Centrifuge db files (I downloaded 3 files : p_compressed+h+v.1.cf, p_compressed+h+v.2.cf and p_compressed+h+v.3.cf : is it correct ?).
I searched with google how to execute the tool (with 'Run' button ? the circle ? ) but I'm quite lost....
With "run" button, I have this message  for the cell In [1] :
```
%matplotlib inline
import matplotlib.pyplot as plt
import os
import numpy as np
import pandas as pd
import seaborn as sns
import csv

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-3dce727767ad> in <module>()
----> 1 get_ipython().magic(u'matplotlib inline')
      2 import matplotlib.pyplot as plt
      3 import os
      4 import numpy as np
      5 import pandas as pd

/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2158         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2159         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2160         return self.run_line_magic(magic_name, magic_arg_s)
   2161 
   2162     #-------------------------------------------------------------------------

/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2079                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2080             with self.builtin_trap:
-> 2081                 result = fn(*args,**kwargs)
   2082             return result
   2083 

<decorator-gen-105> in matplotlib(self, line)

/anaconda2/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/anaconda2/lib/python2.7/site-packages/IPython/core/magics/pylab.pyc in matplotlib(self, line)
     98             print("Available matplotlib backends: %s" % backends_list)
     99         else:
--> 100             gui, backend = self.shell.enable_matplotlib(args.gui)
    101             self._show_matplotlib_backend(args.gui, backend)
    102 

/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in enable_matplotlib(self, gui)
   2952         """
   2953         from IPython.core import pylabtools as pt
-> 2954         gui, backend = pt.find_gui_and_backend(gui, self.pylab_gui_select)
   2955 
   2956         if gui != 'inline':

/anaconda2/lib/python2.7/site-packages/IPython/core/pylabtools.pyc in find_gui_and_backend(gui, gui_select)
    277     """
    278 
--> 279     import matplotlib
    280 
    281     if gui and gui != 'auto':

/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py in <module>()
    124 # cbook must import matplotlib only within function
    125 # definitions, so it is safe to import from it here.
--> 126 from . import cbook
    127 from matplotlib.cbook import (
    128     _backports, mplDeprecation, dedent, get_label, sanitize_sequence)

/anaconda2/lib/python2.7/site-packages/matplotlib/cbook/__init__.py in <module>()
     32 from weakref import ref, WeakKeyDictionary
     33 
---> 34 import numpy as np
     35 
     36 import matplotlib

ImportError: No module named numpy
```

So could you help me to use your tool, please ? Because we waited months (it seems to analyse data as we would like) but I don't get it to work...

So I install numpy.
After, I load a fastq file :
There is this message on the jupyter nb GUI:

`File selected:/Users/2018eb005/Documents/work/byPeople/Emmanuelle/NanoFlow/output_NanoFlow/run_20190411/fastq/barcoder/barcode01/pass/barcode01.fastq`

In the terminal, there is this message :
```
[I 19:14:37.478 NotebookApp] Saving file at /MINDS.ipynb
objc[51667]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffaf26a3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10f08ff50). One of the two will be used. Which one is undefined.
[I 19:16:37.471 NotebookApp] Saving file at /MINDS.ipynb
[I 19:20:37.461 NotebookApp] Saving file at /MINDS.ipynb
```

And in the jupyter notebook, this one :

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-7478a5758f7e> in <module>()
----> 1 samplename_w_ext = os.path.basename(fastq_file)
      2 samplename, file_extension = os.path.splitext(samplename_w_ext)
      3 print(samplename)

NameError: name 'os' is not defined
```

I set  :
```
db_file="~/Applications/MINDS/centrifuge_db/p_compressed+h+v" # doest the script understand all the p_compressed+h+v* files ?
fldresults='~/Applications/MINDS/centrifuge_rslts/'
```

I click on "Run" button several times, to see what appends, and I obtain each time a error message for each next cell, maybe consequently to the first 'os' error:
`NameError: name 'dfResult' is not defined`
`NameError: name 'dfReport' is not defined`
`NameError: name 'dfData' is not defined`
...

So could you help me to use a jupyter environment, please ? Because we waited months (MINDS seems to be perfect for your data and context research) but I don't get it to work for the moment... maybe the installation on my Mac is not perfect too...

Best regards,
Emmanuelle Beyne

**Comment by MINDS-Software** [comment]
Hi,
Sorry to hear about the issues you are having with setting up MINDS environment on your Mac. 

MINDS  is based on Linux OS and some of the modules listed in the requirements.yml file are not supported on Mac by conda. Please use the attached requirements_MacOS.txt to re-create MINDS environment, after downloading the requirements_MacOS.txt file rename the file extension to requirements_MacOS.yml

You will have to remove the existing MINDS env by going to terminal and type:

condo env remove -n MINDS

Then re create the env MINDS using the new  requirements_MacOS.yml

conda env create —file requirements_MacOS.yml

This will solve the issue of “Solving environment: failed” and install all the required modules for MINDS to run and should be able to resolve the modules based errors. Please let me know if you get any error messages, while creating the environment.

You can press ”shift”+“enter” on each cell to execute it and move to next cell, instead of clicking on Run.

As for the centrifuge indexes you have the correct files and have correctly set the db_file.

Thank you for your suggestion on updating the README file and will incorporate suggested  edits.

Hope this will help you to solve the issues.

Best regards,
Samir
[requirements_MacOS.txt](https://github.com/MINDS-Software/MINDS/files/4302041/requirements_MacOS.txt)

**Comment by md342010** [comment]
Thanks a lot for your reactivity, Samir !
I'll try again asap

Best regards,
Emmanuelle

**Comment by md342010** [comment]
Hi Samir,

MINDS is working fine on my Mac, thanks a lot ! I think  your tool should be very  helpful with our data : offline and fast, at least for inter-species identification.

Best regards,
Emmanuelle

**Comment by MINDS-Software** [comment]
Hi Emmanuelle,
Your welcome & glad to hear that MINDS is working on your Mac. 
I will close the issue now and if you have any feature request feel free to let me know and i will try to incorporate them in future release.

Best regards,
Samir
